### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by xfq** [w3c/scribe2#34]
I hope that for the generated mintutes (and docs for Scribe.perl), it would be nice to have dark mode support.

**Comment by xfq** [comment]
I did an experiment here for reference: https://xfq.github.io/dark-mode-minutes/

**Comment by kfranqueiro** [comment]
@bert-github added some initial dark mode styles on June 23. I have a couple of points of feedback to what was applied.

If you agree with the feedback, let me know if you'd like me to make the changes directly.

## Ensure sufficient contrast on Team pages

The background chosen is light enough to cause trouble reading text that is rendered directly against the background, e.g. the top "Meeting Minutes" heading and especially the messages at the bottom of the page.

**Suggestion:** reduce the luminance of the gradient colors from 56% to 41% in `team.css`:

```css
@media (prefers-color-scheme: dark) {
  html {
    background: fixed top right no-repeat url(https://www.w3.org/StyleSheets/team.gif),
      linear-gradient(to right, hsla(0,0%,0%,0.35), hsla(0,0%,0%,0.3),
        hsla(0,0%,0%,0.35)),
      linear-gradient(hsla(37,23%,41%,0.5), hsla(37,23%,41%,1.0)),
      url(https://www.w3.org/StyleSheets/Background/PaperBag.jpg)}
}
```

Example before:

![Off-white text against a light background, making it hard to read.](https://github.com/user-attachments/assets/f8378479-e447-414e-bd3b-4738c4df8480)

Example after:

![Off-white text against a darker background, making it easier to read.](https://github.com/user-attachments/assets/619fbb3a-8c0b-43bf-a3a1-494b42e5d087)

## Revert dark-mode changes to `.bot`

In the current styles, `.bot` was overridden to effectively invert its current effect. The problem is this can cause a sizeable chunk of solid bright background, defeating the point of dark mode (it's useful to remember it's "dark" not "inverted").

I'd suggest at least reverting that change; IIUC Fuqiao's prototype didn't touch these at all either.

**Suggestion: Remove** the following lines from within the `prefers-color-scheme: dark` block in `public.css`:
```css
  .bot {background: hsl(205,70%,71%); color: black}
  .bot :link {color: hsl(200,97%,12%)}
  .bot :visited {color: hsl(281,100%,6%)}
```

Example before:

![Bright blocks with dark text, which stand out excessively against the surrounding dark background.](https://github.com/user-attachments/assets/61d097ab-d226-47cf-8e7b-aa0de98afec5)

Example after:

![Dark blocks with light text, which are much easier on the eyes against the surrounding dark background.](https://github.com/user-attachments/assets/f7444126-e9cb-4693-ad7a-fecd71e99439)
